# -*- coding: utf-8 -*-
"""Trabalho_Detetive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ginaxim/TrabDetetiveBigData/blob/main/Trabalho_Detetive.ipynb
"""

import pandas as pd

df_estoque = pd.read_csv('Estoque.csv', delimiter= ';')
df_heranca = pd.read_csv('Heranca.csv', delimiter= ';')
df_relatos = pd.read_csv('Relatos.csv', delimiter= ';')
df_suspeitos = pd.read_csv('Suspeitos.csv', delimiter= ';')

df_suspeitos.loc[(df_suspeitos['Altura'] >= 165) & (df_suspeitos['Altura'] <= 185) & (df_suspeitos['Cor_do_cabelo'] == "Loiro")]

df_relatos.loc[df_relatos['Nome'].str.contains('Gustavo', case=False)]

df_relatos.loc[df_relatos['Nome'].str.contains('Madalena', case=False)]

df_relatos.query('Ordem == 21')

df_estoque.loc[df_estoque['Data'].str.contains('05',case=False )]

df_estoque.loc[df_estoque['Data'].str.contains('06/06')]

df_estoque.query('Código == "pd7891"')

df_heranca.loc[df_heranca['Herança'] >= 119860]

df_suspeitos.query("Nome == 'Suspeito 109'")

df_suspeitos.loc[(df_suspeitos['Cor_do_cabelo'] == "Loiro") & (df_suspeitos['Mascara'] == "Lobo") & (df_suspeitos['Sexo'] == "H")]

df_suspeitos.loc[(df_suspeitos['Cor_do_cabelo'] == "Loiro") & (df_suspeitos['Mascara'] == "Lobo") & (df_suspeitos['Sexo'] == "M")]

df_heranca.query('Suspeito == "Suspeito 143"')

df_suspeitos.loc[df_suspeitos['Nome'] == "Suspeito 89"]

df_suspeitos.loc[df_suspeitos['Nome'] == "Suspeito 143"]

df_relatos.loc[df_relatos['Máscara'] == "Lobo"]